# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ad5c1b6ec9f35f490cffe999fe51b76050fc1698a199b89050cf85b7f2f1fd1cbcdec04592d3d1d7d9b7ff7e8596799eee69ea0f940ed9cf4a3b87a19377171

test:
  secret_key_base: feffc69a0b58d0cf4fa39f28128089f1ee302f2683de18659fd2cd289aa257bc34523205d67f1ac288b44fc90d6391460b95398b342214c4db1085f586db2c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
